// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services/inputemulation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GRPCServices.Driver {

  /// <summary>Holder for reflection information generated from services/inputemulation.proto</summary>
  public static partial class InputemulationReflection {

    #region Descriptor
    /// <summary>File descriptor for services/inputemulation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InputemulationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1zZXJ2aWNlcy9pbnB1dGVtdWxhdGlvbi5wcm90bxITZ1JQQ1NlcnZpY2Vz",
            "LkRyaXZlchoSaW5jbHVkZS9wb3NlLnByb3RvGhtnb29nbGUvcHJvdG9idWYv",
            "ZW1wdHkucHJvdG8imgEKDUF0dGFjaE1lc3NhZ2USCgoCaWQYASABKAUSOQoG",
            "ZGV2aWNlGAIgASgOMikuZ1JQQ1NlcnZpY2VzLkRyaXZlci5BdHRhY2hNZXNz",
            "YWdlLkRldmljZSJCCgZEZXZpY2USEgoOVU5LTk9XTl9ERVZJQ0UQABIHCgNI",
            "TUQQARILCgdUUkFDS0VSEAISDgoKQ09OVFJPTExFUhADIhsKDURldGFjaE1l",
            "c3NhZ2USCgoCaWQYASABKAUikwEKEFRyYW5zZm9ybU1lc3NhZ2USCgoCaWQY",
            "ASABKAUSKwoIYWJzb2x1dGUYAiABKAsyFy5HcmFwaGljcy5DYXJ0ZXNpYW5Q",
            "b3NlSAASKwoIcmVsYXRpdmUYAyABKAsyFy5HcmFwaGljcy5DYXJ0ZXNpYW5Q",
            "b3NlSABCGQoXcmVsYXRpdmVfYWJzb2x1dGVfb25lb2Yy6AEKDklucHV0RW11",
            "bGF0aW9uEkQKBkF0dGFjaBIiLmdSUENTZXJ2aWNlcy5Ecml2ZXIuQXR0YWNo",
            "TWVzc2FnZRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRJECgZEZXRhY2gSIi5n",
            "UlBDU2VydmljZXMuRHJpdmVyLkRldGFjaE1lc3NhZ2UaFi5nb29nbGUucHJv",
            "dG9idWYuRW1wdHkSSgoJVHJhbnNmb3JtEiUuZ1JQQ1NlcnZpY2VzLkRyaXZl",
            "ci5UcmFuc2Zvcm1NZXNzYWdlGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5YgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Graphics.PoseReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GRPCServices.Driver.AttachMessage), global::GRPCServices.Driver.AttachMessage.Parser, new[]{ "Id", "Device" }, null, new[]{ typeof(global::GRPCServices.Driver.AttachMessage.Types.Device) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GRPCServices.Driver.DetachMessage), global::GRPCServices.Driver.DetachMessage.Parser, new[]{ "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GRPCServices.Driver.TransformMessage), global::GRPCServices.Driver.TransformMessage.Parser, new[]{ "Id", "Absolute", "Relative" }, new[]{ "RelativeAbsoluteOneof" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AttachMessage : pb::IMessage<AttachMessage> {
    private static readonly pb::MessageParser<AttachMessage> _parser = new pb::MessageParser<AttachMessage>(() => new AttachMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AttachMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GRPCServices.Driver.InputemulationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttachMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttachMessage(AttachMessage other) : this() {
      id_ = other.id_;
      device_ = other.device_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttachMessage Clone() {
      return new AttachMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "device" field.</summary>
    public const int DeviceFieldNumber = 2;
    private global::GRPCServices.Driver.AttachMessage.Types.Device device_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GRPCServices.Driver.AttachMessage.Types.Device Device {
      get { return device_; }
      set {
        device_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AttachMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AttachMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Device != other.Device) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Device != 0) hash ^= Device.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Device != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Device);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Device != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Device);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AttachMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Device != 0) {
        Device = other.Device;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Device = (global::GRPCServices.Driver.AttachMessage.Types.Device) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AttachMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Device {
        [pbr::OriginalName("UNKNOWN_DEVICE")] UnknownDevice = 0,
        [pbr::OriginalName("HMD")] Hmd = 1,
        [pbr::OriginalName("TRACKER")] Tracker = 2,
        [pbr::OriginalName("CONTROLLER")] Controller = 3,
      }

    }
    #endregion

  }

  public sealed partial class DetachMessage : pb::IMessage<DetachMessage> {
    private static readonly pb::MessageParser<DetachMessage> _parser = new pb::MessageParser<DetachMessage>(() => new DetachMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DetachMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GRPCServices.Driver.InputemulationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DetachMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DetachMessage(DetachMessage other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DetachMessage Clone() {
      return new DetachMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DetachMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DetachMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DetachMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class TransformMessage : pb::IMessage<TransformMessage> {
    private static readonly pb::MessageParser<TransformMessage> _parser = new pb::MessageParser<TransformMessage>(() => new TransformMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TransformMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GRPCServices.Driver.InputemulationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformMessage(TransformMessage other) : this() {
      id_ = other.id_;
      switch (other.RelativeAbsoluteOneofCase) {
        case RelativeAbsoluteOneofOneofCase.Absolute:
          Absolute = other.Absolute.Clone();
          break;
        case RelativeAbsoluteOneofOneofCase.Relative:
          Relative = other.Relative.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransformMessage Clone() {
      return new TransformMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "absolute" field.</summary>
    public const int AbsoluteFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Graphics.CartesianPose Absolute {
      get { return relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Absolute ? (global::Graphics.CartesianPose) relativeAbsoluteOneof_ : null; }
      set {
        relativeAbsoluteOneof_ = value;
        relativeAbsoluteOneofCase_ = value == null ? RelativeAbsoluteOneofOneofCase.None : RelativeAbsoluteOneofOneofCase.Absolute;
      }
    }

    /// <summary>Field number for the "relative" field.</summary>
    public const int RelativeFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Graphics.CartesianPose Relative {
      get { return relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Relative ? (global::Graphics.CartesianPose) relativeAbsoluteOneof_ : null; }
      set {
        relativeAbsoluteOneof_ = value;
        relativeAbsoluteOneofCase_ = value == null ? RelativeAbsoluteOneofOneofCase.None : RelativeAbsoluteOneofOneofCase.Relative;
      }
    }

    private object relativeAbsoluteOneof_;
    /// <summary>Enum of possible cases for the "relative_absolute_oneof" oneof.</summary>
    public enum RelativeAbsoluteOneofOneofCase {
      None = 0,
      Absolute = 2,
      Relative = 3,
    }
    private RelativeAbsoluteOneofOneofCase relativeAbsoluteOneofCase_ = RelativeAbsoluteOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RelativeAbsoluteOneofOneofCase RelativeAbsoluteOneofCase {
      get { return relativeAbsoluteOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRelativeAbsoluteOneof() {
      relativeAbsoluteOneofCase_ = RelativeAbsoluteOneofOneofCase.None;
      relativeAbsoluteOneof_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TransformMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TransformMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Absolute, other.Absolute)) return false;
      if (!object.Equals(Relative, other.Relative)) return false;
      if (RelativeAbsoluteOneofCase != other.RelativeAbsoluteOneofCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Absolute) hash ^= Absolute.GetHashCode();
      if (relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Relative) hash ^= Relative.GetHashCode();
      hash ^= (int) relativeAbsoluteOneofCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Absolute) {
        output.WriteRawTag(18);
        output.WriteMessage(Absolute);
      }
      if (relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Relative) {
        output.WriteRawTag(26);
        output.WriteMessage(Relative);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Absolute) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Absolute);
      }
      if (relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Relative) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Relative);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TransformMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      switch (other.RelativeAbsoluteOneofCase) {
        case RelativeAbsoluteOneofOneofCase.Absolute:
          if (Absolute == null) {
            Absolute = new global::Graphics.CartesianPose();
          }
          Absolute.MergeFrom(other.Absolute);
          break;
        case RelativeAbsoluteOneofOneofCase.Relative:
          if (Relative == null) {
            Relative = new global::Graphics.CartesianPose();
          }
          Relative.MergeFrom(other.Relative);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            global::Graphics.CartesianPose subBuilder = new global::Graphics.CartesianPose();
            if (relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Absolute) {
              subBuilder.MergeFrom(Absolute);
            }
            input.ReadMessage(subBuilder);
            Absolute = subBuilder;
            break;
          }
          case 26: {
            global::Graphics.CartesianPose subBuilder = new global::Graphics.CartesianPose();
            if (relativeAbsoluteOneofCase_ == RelativeAbsoluteOneofOneofCase.Relative) {
              subBuilder.MergeFrom(Relative);
            }
            input.ReadMessage(subBuilder);
            Relative = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
