// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services/inputemulation.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GRPCServices.Driver {
  public static partial class InputEmulation
  {
    static readonly string __ServiceName = "gRPCServices.Driver.InputEmulation";

    static readonly grpc::Marshaller<global::GRPCServices.Driver.AttachMessage> __Marshaller_gRPCServices_Driver_AttachMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCServices.Driver.AttachMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCServices.Driver.DetachMessage> __Marshaller_gRPCServices_Driver_DetachMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCServices.Driver.DetachMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCServices.Driver.TransformMessage> __Marshaller_gRPCServices_Driver_TransformMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCServices.Driver.TransformMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::GRPCServices.Driver.AttachMessage, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Attach = new grpc::Method<global::GRPCServices.Driver.AttachMessage, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Attach",
        __Marshaller_gRPCServices_Driver_AttachMessage,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::GRPCServices.Driver.DetachMessage, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Detach = new grpc::Method<global::GRPCServices.Driver.DetachMessage, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Detach",
        __Marshaller_gRPCServices_Driver_DetachMessage,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::GRPCServices.Driver.TransformMessage, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Transform = new grpc::Method<global::GRPCServices.Driver.TransformMessage, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Transform",
        __Marshaller_gRPCServices_Driver_TransformMessage,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GRPCServices.Driver.InputemulationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of InputEmulation</summary>
    [grpc::BindServiceMethod(typeof(InputEmulation), "BindService")]
    public abstract partial class InputEmulationBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Attach(global::GRPCServices.Driver.AttachMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Detach(global::GRPCServices.Driver.DetachMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Transform(global::GRPCServices.Driver.TransformMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InputEmulation</summary>
    public partial class InputEmulationClient : grpc::ClientBase<InputEmulationClient>
    {
      /// <summary>Creates a new client for InputEmulation</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public InputEmulationClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InputEmulation that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public InputEmulationClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected InputEmulationClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected InputEmulationClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Google.Protobuf.WellKnownTypes.Empty Attach(global::GRPCServices.Driver.AttachMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Attach(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Attach(global::GRPCServices.Driver.AttachMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Attach, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> AttachAsync(global::GRPCServices.Driver.AttachMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AttachAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> AttachAsync(global::GRPCServices.Driver.AttachMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Attach, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Detach(global::GRPCServices.Driver.DetachMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Detach(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Detach(global::GRPCServices.Driver.DetachMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Detach, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DetachAsync(global::GRPCServices.Driver.DetachMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DetachAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DetachAsync(global::GRPCServices.Driver.DetachMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Detach, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Transform(global::GRPCServices.Driver.TransformMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Transform(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Transform(global::GRPCServices.Driver.TransformMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Transform, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TransformAsync(global::GRPCServices.Driver.TransformMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransformAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TransformAsync(global::GRPCServices.Driver.TransformMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Transform, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override InputEmulationClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InputEmulationClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(InputEmulationBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Attach, serviceImpl.Attach)
          .AddMethod(__Method_Detach, serviceImpl.Detach)
          .AddMethod(__Method_Transform, serviceImpl.Transform).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, InputEmulationBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Attach, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GRPCServices.Driver.AttachMessage, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Attach));
      serviceBinder.AddMethod(__Method_Detach, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GRPCServices.Driver.DetachMessage, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Detach));
      serviceBinder.AddMethod(__Method_Transform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GRPCServices.Driver.TransformMessage, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Transform));
    }

  }
}
#endregion
