// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services/ping.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GRPCServices.Ping {
  public static partial class PingService
  {
    static readonly string __ServiceName = "gRPCServices.ping.PingService";

    static readonly grpc::Marshaller<global::GRPCServices.Ping.PingRequest> __Marshaller_gRPCServices_ping_PingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCServices.Ping.PingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCServices.Ping.PingResponse> __Marshaller_gRPCServices_ping_PingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCServices.Ping.PingResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::GRPCServices.Ping.PingRequest, global::GRPCServices.Ping.PingResponse> __Method_Ping = new grpc::Method<global::GRPCServices.Ping.PingRequest, global::GRPCServices.Ping.PingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_gRPCServices_ping_PingRequest,
        __Marshaller_gRPCServices_ping_PingResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GRPCServices.Ping.PingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PingService</summary>
    [grpc::BindServiceMethod(typeof(PingService), "BindService")]
    public abstract partial class PingServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GRPCServices.Ping.PingResponse> Ping(global::GRPCServices.Ping.PingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PingService</summary>
    public partial class PingServiceClient : grpc::ClientBase<PingServiceClient>
    {
      /// <summary>Creates a new client for PingService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PingServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PingService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PingServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PingServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PingServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GRPCServices.Ping.PingResponse Ping(global::GRPCServices.Ping.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GRPCServices.Ping.PingResponse Ping(global::GRPCServices.Ping.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCServices.Ping.PingResponse> PingAsync(global::GRPCServices.Ping.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCServices.Ping.PingResponse> PingAsync(global::GRPCServices.Ping.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PingServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PingServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PingServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ping, serviceImpl.Ping).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PingServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Ping, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GRPCServices.Ping.PingRequest, global::GRPCServices.Ping.PingResponse>(serviceImpl.Ping));
    }

  }
}
#endregion
